name: .NET CD

on:
  push:
    branches: [ "main" ]
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore ./Exercicio/DependencyRoomBooking.sln
      - name: Build
        run: dotnet build --no-restore
      - name: Repositories Tests
        run: dotnet test --no-build --verbosity normal ./Exercicio/Repositories_UnitTests/Repositories_UnitTests.csproj
      - name: Converters Tests
        run: dotnet test --no-build --verbosity normal ./Exercicio/Converters_UnitTests/Converters_UnitTests.csproj
      - name: Handler Tests
        run: dotnet test --no-build --verbosity normal ./Exercicio/Handler_UnitTests/Handler_UnitTests.csproj
      - name: Fake Repositories Tests
        run: dotnet test --no-build --verbosity normal ./Exercicio/FakeRepositories_UnitTests/FakeRepositories_UnitTests.csproj
      - name: Fake Infrastructure Services Tests
        run: dotnet test --no-build --verbosity normal ./Exercicio/FakeInfrastructureServices_UnitTests/FakeInfrastructureServices_UnitTests.csproj

  deploy: 

    runs-on: ubuntu-latest
    needs: test
    if: success() && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
